// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF71f0167DecodeGithubComGui774umeKriePkgKrieEvents(in *jlexer.Lexer, out *EventCheckEventSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.EventCheckEvent = new(EventCheckEvent)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "checked_event_type":
			out.CheckedEventType = EventType(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF71f0167EncodeGithubComGui774umeKriePkgKrieEvents(out *jwriter.Writer, in EventCheckEventSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"checked_event_type\":"
		out.RawString(prefix[1:])
		out.Raw((in.CheckedEventType).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventCheckEventSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF71f0167EncodeGithubComGui774umeKriePkgKrieEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventCheckEventSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF71f0167DecodeGithubComGui774umeKriePkgKrieEvents(l, v)
}
