// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson39669e3DecodeGithubComGui774umeKriePkgKrieEvents(in *jlexer.Lexer, out *KernelParameterEventSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.KernelParameterEvent = new(KernelParameterEvent)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "parameter":
			easyjson39669e3DecodeGithubComGui774umeKriePkgKrieEvents1(in, &out.Parameter)
		case "expected_value":
			out.ExpectedValue = uint64(in.Uint64())
		case "actual_value":
			out.ActualValue = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson39669e3EncodeGithubComGui774umeKriePkgKrieEvents(out *jwriter.Writer, in KernelParameterEventSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"parameter\":"
		first = false
		out.RawString(prefix[1:])
		easyjson39669e3EncodeGithubComGui774umeKriePkgKrieEvents1(out, in.Parameter)
	}
	{
		const prefix string = ",\"expected_value\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.ExpectedValue))
	}
	{
		const prefix string = ",\"actual_value\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ActualValue))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KernelParameterEventSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson39669e3EncodeGithubComGui774umeKriePkgKrieEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KernelParameterEventSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson39669e3DecodeGithubComGui774umeKriePkgKrieEvents(l, v)
}
func easyjson39669e3DecodeGithubComGui774umeKriePkgKrieEvents1(in *jlexer.Lexer, out *KernelSymbol) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = MemoryPointer(in.Uint64())
		case "symbol":
			out.Symbol = string(in.String())
		case "module":
			out.Module = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson39669e3EncodeGithubComGui774umeKriePkgKrieEvents1(out *jwriter.Writer, in KernelSymbol) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Address != 0 {
		const prefix string = ",\"address\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((in.Address).MarshalJSON())
	}
	if in.Symbol != "" {
		const prefix string = ",\"symbol\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Symbol))
	}
	if in.Module != "" {
		const prefix string = ",\"module\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Module))
	}
	out.RawByte('}')
}
