// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6d00de40DecodeGithubComGui774umeKriePkgKrieEvents(in *jlexer.Lexer, out *InitModuleSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.InitModule = new(InitModule)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "loaded_from_memory":
			out.LoadedFromMemory = bool(in.Bool())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6d00de40EncodeGithubComGui774umeKriePkgKrieEvents(out *jwriter.Writer, in InitModuleSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"loaded_from_memory\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.LoadedFromMemory))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InitModuleSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6d00de40EncodeGithubComGui774umeKriePkgKrieEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InitModuleSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6d00de40DecodeGithubComGui774umeKriePkgKrieEvents(l, v)
}
func easyjson6d00de40DecodeGithubComGui774umeKriePkgKrieEvents1(in *jlexer.Lexer, out *DeleteModuleSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.DeleteModule = new(DeleteModule)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6d00de40EncodeGithubComGui774umeKriePkgKrieEvents1(out *jwriter.Writer, in DeleteModuleSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteModuleSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6d00de40EncodeGithubComGui774umeKriePkgKrieEvents1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteModuleSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6d00de40DecodeGithubComGui774umeKriePkgKrieEvents1(l, v)
}
