/*
Copyright © 2022 GUILLAUME FOURNIER

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package events

import (
	manager "github.com/DataDog/ebpf-manager"
)

func addLSMProbes(all *[]*manager.Probe) {
	*all = append(*all, []*manager.Probe{
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_set_context_mgr", EBPFFuncName: "lsm_security_binder_set_context_mgr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_transaction", EBPFFuncName: "lsm_security_binder_transaction"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_transfer_binder", EBPFFuncName: "lsm_security_binder_transfer_binder"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_transfer_file", EBPFFuncName: "lsm_security_binder_transfer_file"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ptrace_access_check", EBPFFuncName: "lsm_security_ptrace_access_check"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ptrace_traceme", EBPFFuncName: "lsm_security_ptrace_traceme"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/capget", EBPFFuncName: "lsm_security_capget"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/capset", EBPFFuncName: "lsm_security_capset"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/capable", EBPFFuncName: "lsm_security_capable"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/quotactl", EBPFFuncName: "lsm_security_quotactl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/quota_on", EBPFFuncName: "lsm_security_quota_on"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/syslog", EBPFFuncName: "lsm_security_syslog"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bprm_creds_for_exec", EBPFFuncName: "lsm_security_bprm_creds_for_exec"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bprm_creds_from_file", EBPFFuncName: "lsm_security_bprm_creds_from_file"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/fs_context_dup", EBPFFuncName: "lsm_security_fs_context_dup"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/fs_context_parse_param", EBPFFuncName: "lsm_security_fs_context_parse_param"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_eat_lsm_opts", EBPFFuncName: "lsm_security_sb_eat_lsm_opts"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_mnt_opts_compat", EBPFFuncName: "lsm_security_sb_mnt_opts_compat"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_remount", EBPFFuncName: "lsm_security_sb_remount"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_kern_mount", EBPFFuncName: "lsm_security_sb_kern_mount"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_show_options", EBPFFuncName: "lsm_security_sb_show_options"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_statfs", EBPFFuncName: "lsm_security_sb_statfs"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_mount", EBPFFuncName: "lsm_security_sb_mount"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_umount", EBPFFuncName: "lsm_security_sb_umount"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_pivotroot", EBPFFuncName: "lsm_security_sb_pivotroot"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_set_mnt_opts", EBPFFuncName: "lsm_security_sb_set_mnt_opts"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_clone_mnt_opts", EBPFFuncName: "lsm_security_sb_clone_mnt_opts"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/move_mount", EBPFFuncName: "lsm_security_move_mount"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/dentry_init_security", EBPFFuncName: "lsm_security_dentry_init_security"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/dentry_create_files_as", EBPFFuncName: "lsm_security_dentry_create_files_as"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/path_notify", EBPFFuncName: "lsm_security_path_notify"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_init_security", EBPFFuncName: "lsm_security_inode_init_security"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_init_security_anon", EBPFFuncName: "lsm_security_inode_init_security_anon"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_create", EBPFFuncName: "lsm_security_inode_create"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_link", EBPFFuncName: "lsm_security_inode_link"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_unlink", EBPFFuncName: "lsm_security_inode_unlink"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_symlink", EBPFFuncName: "lsm_security_inode_symlink"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_mkdir", EBPFFuncName: "lsm_security_inode_mkdir"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_rmdir", EBPFFuncName: "lsm_security_inode_rmdir"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_mknod", EBPFFuncName: "lsm_security_inode_mknod"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_rename", EBPFFuncName: "lsm_security_inode_rename"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_readlink", EBPFFuncName: "lsm_security_inode_readlink"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_follow_link", EBPFFuncName: "lsm_security_inode_follow_link"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_permission", EBPFFuncName: "lsm_security_inode_permission"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setattr", EBPFFuncName: "lsm_security_inode_setattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getattr", EBPFFuncName: "lsm_security_inode_getattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setxattr", EBPFFuncName: "lsm_security_inode_setxattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getxattr", EBPFFuncName: "lsm_security_inode_getxattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_listxattr", EBPFFuncName: "lsm_security_inode_listxattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_removexattr", EBPFFuncName: "lsm_security_inode_removexattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_need_killpriv", EBPFFuncName: "lsm_security_inode_need_killpriv"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_killpriv", EBPFFuncName: "lsm_security_inode_killpriv"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getsecurity", EBPFFuncName: "lsm_security_inode_getsecurity"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setsecurity", EBPFFuncName: "lsm_security_inode_setsecurity"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_listsecurity", EBPFFuncName: "lsm_security_inode_listsecurity"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_copy_up", EBPFFuncName: "lsm_security_inode_copy_up"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_copy_up_xattr", EBPFFuncName: "lsm_security_inode_copy_up_xattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernfs_init_security", EBPFFuncName: "lsm_security_kernfs_init_security"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_permission", EBPFFuncName: "lsm_security_file_permission"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_ioctl", EBPFFuncName: "lsm_security_file_ioctl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/mmap_file", EBPFFuncName: "lsm_security_mmap_file"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/mmap_addr", EBPFFuncName: "lsm_security_mmap_addr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_mprotect", EBPFFuncName: "lsm_security_file_mprotect"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_lock", EBPFFuncName: "lsm_security_file_lock"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_fcntl", EBPFFuncName: "lsm_security_file_fcntl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_send_sigiotask", EBPFFuncName: "lsm_security_file_send_sigiotask"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_receive", EBPFFuncName: "lsm_security_file_receive"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_open", EBPFFuncName: "lsm_security_file_open"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_alloc", EBPFFuncName: "lsm_security_task_alloc"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/cred_alloc_blank", EBPFFuncName: "lsm_security_cred_alloc_blank"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_act_as", EBPFFuncName: "lsm_security_kernel_act_as"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_create_files_as", EBPFFuncName: "lsm_security_kernel_create_files_as"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_module_request", EBPFFuncName: "lsm_security_kernel_module_request"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_load_data", EBPFFuncName: "lsm_security_kernel_load_data"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_post_load_data", EBPFFuncName: "lsm_security_kernel_post_load_data"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_read_file", EBPFFuncName: "lsm_security_kernel_read_file"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_post_read_file", EBPFFuncName: "lsm_security_kernel_post_read_file"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_fix_setuid", EBPFFuncName: "lsm_security_task_fix_setuid"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_fix_setgid", EBPFFuncName: "lsm_security_task_fix_setgid"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setpgid", EBPFFuncName: "lsm_security_task_setpgid"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getpgid", EBPFFuncName: "lsm_security_task_getpgid"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getsid", EBPFFuncName: "lsm_security_task_getsid"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setnice", EBPFFuncName: "lsm_security_task_setnice"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setioprio", EBPFFuncName: "lsm_security_task_setioprio"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getioprio", EBPFFuncName: "lsm_security_task_getioprio"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_prlimit", EBPFFuncName: "lsm_security_task_prlimit"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setrlimit", EBPFFuncName: "lsm_security_task_setrlimit"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setscheduler", EBPFFuncName: "lsm_security_task_setscheduler"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getscheduler", EBPFFuncName: "lsm_security_task_getscheduler"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_movememory", EBPFFuncName: "lsm_security_task_movememory"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_kill", EBPFFuncName: "lsm_security_task_kill"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_prctl", EBPFFuncName: "lsm_security_task_prctl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ipc_permission", EBPFFuncName: "lsm_security_ipc_permission"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_associate", EBPFFuncName: "lsm_security_msg_queue_associate"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_msgctl", EBPFFuncName: "lsm_security_msg_queue_msgctl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_msgsnd", EBPFFuncName: "lsm_security_msg_queue_msgsnd"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_msgrcv", EBPFFuncName: "lsm_security_msg_queue_msgrcv"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/shm_associate", EBPFFuncName: "lsm_security_shm_associate"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/shm_shmctl", EBPFFuncName: "lsm_security_shm_shmctl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/shm_shmat", EBPFFuncName: "lsm_security_shm_shmat"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sem_associate", EBPFFuncName: "lsm_security_sem_associate"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sem_semctl", EBPFFuncName: "lsm_security_sem_semctl"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sem_semop", EBPFFuncName: "lsm_security_sem_semop"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/getprocattr", EBPFFuncName: "lsm_security_getprocattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/setprocattr", EBPFFuncName: "lsm_security_setprocattr"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/netlink_send", EBPFFuncName: "lsm_security_netlink_send"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ismaclabel", EBPFFuncName: "lsm_security_ismaclabel"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/secid_to_secctx", EBPFFuncName: "lsm_security_secid_to_secctx"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/secctx_to_secid", EBPFFuncName: "lsm_security_secctx_to_secid"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_notifysecctx", EBPFFuncName: "lsm_security_inode_notifysecctx"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setsecctx", EBPFFuncName: "lsm_security_inode_setsecctx"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getsecctx", EBPFFuncName: "lsm_security_inode_getsecctx"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/locked_down", EBPFFuncName: "lsm_security_locked_down"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bpf", EBPFFuncName: "lsm_security_bpf"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bpf_map", EBPFFuncName: "lsm_security_bpf_map"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bpf_prog", EBPFFuncName: "lsm_security_bpf_prog"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_open", EBPFFuncName: "lsm_security_perf_event_open"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_alloc", EBPFFuncName: "lsm_security_perf_event_alloc"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_free", EBPFFuncName: "lsm_security_perf_event_free"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_read", EBPFFuncName: "lsm_security_perf_event_read"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_write", EBPFFuncName: "lsm_security_perf_event_write"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/unix_stream_connect", EBPFFuncName: "lsm_security_unix_stream_connect"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/unix_may_send", EBPFFuncName: "lsm_security_unix_may_send"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_create", EBPFFuncName: "lsm_security_socket_create"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_post_create", EBPFFuncName: "lsm_security_socket_post_create"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_socketpair", EBPFFuncName: "lsm_security_socket_socketpair"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_bind", EBPFFuncName: "lsm_security_socket_bind"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_connect", EBPFFuncName: "lsm_security_socket_connect"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_listen", EBPFFuncName: "lsm_security_socket_listen"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_accept", EBPFFuncName: "lsm_security_socket_accept"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_sendmsg", EBPFFuncName: "lsm_security_socket_sendmsg"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_recvmsg", EBPFFuncName: "lsm_security_socket_recvmsg"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getsockname", EBPFFuncName: "lsm_security_socket_getsockname"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getpeername", EBPFFuncName: "lsm_security_socket_getpeername"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getsockopt", EBPFFuncName: "lsm_security_socket_getsockopt"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_setsockopt", EBPFFuncName: "lsm_security_socket_setsockopt"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_shutdown", EBPFFuncName: "lsm_security_socket_shutdown"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getpeersec_stream", EBPFFuncName: "lsm_security_socket_getpeersec_stream"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getpeersec_dgram", EBPFFuncName: "lsm_security_socket_getpeersec_dgram"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inet_conn_request", EBPFFuncName: "lsm_security_inet_conn_request"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/secmark_relabel_packet", EBPFFuncName: "lsm_security_secmark_relabel_packet"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_alloc_security", EBPFFuncName: "lsm_security_tun_dev_alloc_security"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_create", EBPFFuncName: "lsm_security_tun_dev_create"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_attach_queue", EBPFFuncName: "lsm_security_tun_dev_attach_queue"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_attach", EBPFFuncName: "lsm_security_tun_dev_attach"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_open", EBPFFuncName: "lsm_security_tun_dev_open"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sctp_assoc_request", EBPFFuncName: "lsm_security_sctp_assoc_request"}},
		{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sctp_bind_connect", EBPFFuncName: "lsm_security_sctp_bind_connect"}},
	}...)
}

func addLSMSelectors(all *[]manager.ProbesSelector) {
	*all = append(*all,
		&manager.BestEffort{Selectors: []manager.ProbesSelector{
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_set_context_mgr", EBPFFuncName: "lsm_security_binder_set_context_mgr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_transaction", EBPFFuncName: "lsm_security_binder_transaction"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_transfer_binder", EBPFFuncName: "lsm_security_binder_transfer_binder"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/binder_transfer_file", EBPFFuncName: "lsm_security_binder_transfer_file"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ptrace_access_check", EBPFFuncName: "lsm_security_ptrace_access_check"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ptrace_traceme", EBPFFuncName: "lsm_security_ptrace_traceme"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/capget", EBPFFuncName: "lsm_security_capget"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/capset", EBPFFuncName: "lsm_security_capset"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/capable", EBPFFuncName: "lsm_security_capable"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/quotactl", EBPFFuncName: "lsm_security_quotactl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/quota_on", EBPFFuncName: "lsm_security_quota_on"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/syslog", EBPFFuncName: "lsm_security_syslog"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bprm_creds_for_exec", EBPFFuncName: "lsm_security_bprm_creds_for_exec"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bprm_creds_from_file", EBPFFuncName: "lsm_security_bprm_creds_from_file"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/fs_context_dup", EBPFFuncName: "lsm_security_fs_context_dup"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/fs_context_parse_param", EBPFFuncName: "lsm_security_fs_context_parse_param"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_eat_lsm_opts", EBPFFuncName: "lsm_security_sb_eat_lsm_opts"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_mnt_opts_compat", EBPFFuncName: "lsm_security_sb_mnt_opts_compat"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_remount", EBPFFuncName: "lsm_security_sb_remount"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_kern_mount", EBPFFuncName: "lsm_security_sb_kern_mount"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_show_options", EBPFFuncName: "lsm_security_sb_show_options"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_statfs", EBPFFuncName: "lsm_security_sb_statfs"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_mount", EBPFFuncName: "lsm_security_sb_mount"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_umount", EBPFFuncName: "lsm_security_sb_umount"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_pivotroot", EBPFFuncName: "lsm_security_sb_pivotroot"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_set_mnt_opts", EBPFFuncName: "lsm_security_sb_set_mnt_opts"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sb_clone_mnt_opts", EBPFFuncName: "lsm_security_sb_clone_mnt_opts"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/move_mount", EBPFFuncName: "lsm_security_move_mount"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/dentry_init_security", EBPFFuncName: "lsm_security_dentry_init_security"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/dentry_create_files_as", EBPFFuncName: "lsm_security_dentry_create_files_as"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/path_notify", EBPFFuncName: "lsm_security_path_notify"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_init_security", EBPFFuncName: "lsm_security_inode_init_security"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_init_security_anon", EBPFFuncName: "lsm_security_inode_init_security_anon"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_create", EBPFFuncName: "lsm_security_inode_create"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_link", EBPFFuncName: "lsm_security_inode_link"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_unlink", EBPFFuncName: "lsm_security_inode_unlink"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_symlink", EBPFFuncName: "lsm_security_inode_symlink"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_mkdir", EBPFFuncName: "lsm_security_inode_mkdir"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_rmdir", EBPFFuncName: "lsm_security_inode_rmdir"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_mknod", EBPFFuncName: "lsm_security_inode_mknod"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_rename", EBPFFuncName: "lsm_security_inode_rename"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_readlink", EBPFFuncName: "lsm_security_inode_readlink"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_follow_link", EBPFFuncName: "lsm_security_inode_follow_link"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_permission", EBPFFuncName: "lsm_security_inode_permission"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setattr", EBPFFuncName: "lsm_security_inode_setattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getattr", EBPFFuncName: "lsm_security_inode_getattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setxattr", EBPFFuncName: "lsm_security_inode_setxattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getxattr", EBPFFuncName: "lsm_security_inode_getxattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_listxattr", EBPFFuncName: "lsm_security_inode_listxattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_removexattr", EBPFFuncName: "lsm_security_inode_removexattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_need_killpriv", EBPFFuncName: "lsm_security_inode_need_killpriv"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_killpriv", EBPFFuncName: "lsm_security_inode_killpriv"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getsecurity", EBPFFuncName: "lsm_security_inode_getsecurity"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setsecurity", EBPFFuncName: "lsm_security_inode_setsecurity"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_listsecurity", EBPFFuncName: "lsm_security_inode_listsecurity"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_copy_up", EBPFFuncName: "lsm_security_inode_copy_up"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_copy_up_xattr", EBPFFuncName: "lsm_security_inode_copy_up_xattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernfs_init_security", EBPFFuncName: "lsm_security_kernfs_init_security"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_permission", EBPFFuncName: "lsm_security_file_permission"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_ioctl", EBPFFuncName: "lsm_security_file_ioctl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/mmap_file", EBPFFuncName: "lsm_security_mmap_file"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/mmap_addr", EBPFFuncName: "lsm_security_mmap_addr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_mprotect", EBPFFuncName: "lsm_security_file_mprotect"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_lock", EBPFFuncName: "lsm_security_file_lock"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_fcntl", EBPFFuncName: "lsm_security_file_fcntl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_send_sigiotask", EBPFFuncName: "lsm_security_file_send_sigiotask"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_receive", EBPFFuncName: "lsm_security_file_receive"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/file_open", EBPFFuncName: "lsm_security_file_open"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_alloc", EBPFFuncName: "lsm_security_task_alloc"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/cred_alloc_blank", EBPFFuncName: "lsm_security_cred_alloc_blank"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_act_as", EBPFFuncName: "lsm_security_kernel_act_as"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_create_files_as", EBPFFuncName: "lsm_security_kernel_create_files_as"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_module_request", EBPFFuncName: "lsm_security_kernel_module_request"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_load_data", EBPFFuncName: "lsm_security_kernel_load_data"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_post_load_data", EBPFFuncName: "lsm_security_kernel_post_load_data"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_read_file", EBPFFuncName: "lsm_security_kernel_read_file"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/kernel_post_read_file", EBPFFuncName: "lsm_security_kernel_post_read_file"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_fix_setuid", EBPFFuncName: "lsm_security_task_fix_setuid"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_fix_setgid", EBPFFuncName: "lsm_security_task_fix_setgid"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setpgid", EBPFFuncName: "lsm_security_task_setpgid"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getpgid", EBPFFuncName: "lsm_security_task_getpgid"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getsid", EBPFFuncName: "lsm_security_task_getsid"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setnice", EBPFFuncName: "lsm_security_task_setnice"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setioprio", EBPFFuncName: "lsm_security_task_setioprio"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getioprio", EBPFFuncName: "lsm_security_task_getioprio"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_prlimit", EBPFFuncName: "lsm_security_task_prlimit"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setrlimit", EBPFFuncName: "lsm_security_task_setrlimit"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_setscheduler", EBPFFuncName: "lsm_security_task_setscheduler"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_getscheduler", EBPFFuncName: "lsm_security_task_getscheduler"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_movememory", EBPFFuncName: "lsm_security_task_movememory"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_kill", EBPFFuncName: "lsm_security_task_kill"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/task_prctl", EBPFFuncName: "lsm_security_task_prctl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ipc_permission", EBPFFuncName: "lsm_security_ipc_permission"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_associate", EBPFFuncName: "lsm_security_msg_queue_associate"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_msgctl", EBPFFuncName: "lsm_security_msg_queue_msgctl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_msgsnd", EBPFFuncName: "lsm_security_msg_queue_msgsnd"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/msg_queue_msgrcv", EBPFFuncName: "lsm_security_msg_queue_msgrcv"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/shm_associate", EBPFFuncName: "lsm_security_shm_associate"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/shm_shmctl", EBPFFuncName: "lsm_security_shm_shmctl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/shm_shmat", EBPFFuncName: "lsm_security_shm_shmat"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sem_associate", EBPFFuncName: "lsm_security_sem_associate"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sem_semctl", EBPFFuncName: "lsm_security_sem_semctl"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sem_semop", EBPFFuncName: "lsm_security_sem_semop"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/getprocattr", EBPFFuncName: "lsm_security_getprocattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/setprocattr", EBPFFuncName: "lsm_security_setprocattr"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/netlink_send", EBPFFuncName: "lsm_security_netlink_send"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/ismaclabel", EBPFFuncName: "lsm_security_ismaclabel"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/secid_to_secctx", EBPFFuncName: "lsm_security_secid_to_secctx"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/secctx_to_secid", EBPFFuncName: "lsm_security_secctx_to_secid"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_notifysecctx", EBPFFuncName: "lsm_security_inode_notifysecctx"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_setsecctx", EBPFFuncName: "lsm_security_inode_setsecctx"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inode_getsecctx", EBPFFuncName: "lsm_security_inode_getsecctx"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/locked_down", EBPFFuncName: "lsm_security_locked_down"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bpf", EBPFFuncName: "lsm_security_bpf"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bpf_map", EBPFFuncName: "lsm_security_bpf_map"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/bpf_prog", EBPFFuncName: "lsm_security_bpf_prog"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_open", EBPFFuncName: "lsm_security_perf_event_open"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_alloc", EBPFFuncName: "lsm_security_perf_event_alloc"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_free", EBPFFuncName: "lsm_security_perf_event_free"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_read", EBPFFuncName: "lsm_security_perf_event_read"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/perf_event_write", EBPFFuncName: "lsm_security_perf_event_write"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/unix_stream_connect", EBPFFuncName: "lsm_security_unix_stream_connect"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/unix_may_send", EBPFFuncName: "lsm_security_unix_may_send"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_create", EBPFFuncName: "lsm_security_socket_create"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_post_create", EBPFFuncName: "lsm_security_socket_post_create"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_socketpair", EBPFFuncName: "lsm_security_socket_socketpair"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_bind", EBPFFuncName: "lsm_security_socket_bind"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_connect", EBPFFuncName: "lsm_security_socket_connect"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_listen", EBPFFuncName: "lsm_security_socket_listen"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_accept", EBPFFuncName: "lsm_security_socket_accept"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_sendmsg", EBPFFuncName: "lsm_security_socket_sendmsg"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_recvmsg", EBPFFuncName: "lsm_security_socket_recvmsg"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getsockname", EBPFFuncName: "lsm_security_socket_getsockname"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getpeername", EBPFFuncName: "lsm_security_socket_getpeername"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getsockopt", EBPFFuncName: "lsm_security_socket_getsockopt"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_setsockopt", EBPFFuncName: "lsm_security_socket_setsockopt"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_shutdown", EBPFFuncName: "lsm_security_socket_shutdown"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getpeersec_stream", EBPFFuncName: "lsm_security_socket_getpeersec_stream"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/socket_getpeersec_dgram", EBPFFuncName: "lsm_security_socket_getpeersec_dgram"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/inet_conn_request", EBPFFuncName: "lsm_security_inet_conn_request"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/secmark_relabel_packet", EBPFFuncName: "lsm_security_secmark_relabel_packet"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_alloc_security", EBPFFuncName: "lsm_security_tun_dev_alloc_security"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_create", EBPFFuncName: "lsm_security_tun_dev_create"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_attach_queue", EBPFFuncName: "lsm_security_tun_dev_attach_queue"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_attach", EBPFFuncName: "lsm_security_tun_dev_attach"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/tun_dev_open", EBPFFuncName: "lsm_security_tun_dev_open"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sctp_assoc_request", EBPFFuncName: "lsm_security_sctp_assoc_request"}},
			&manager.ProbeSelector{ProbeIdentificationPair: manager.ProbeIdentificationPair{UID: KRIEUID, EBPFSection: "lsm/sctp_bind_connect", EBPFFuncName: "lsm_security_sctp_bind_connect"}},
		}},
	)
}
