// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB7dd357DecodeGithubComGui774umeKriePkgKrieEvents(in *jlexer.Lexer, out *PtraceEventSerializer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	out.PTraceEvent = new(PTraceEvent)
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = MemoryPointer(in.Uint64())
		case "request":
			out.Request = PTraceRequest(in.Uint32())
		case "pid":
			out.PID = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB7dd357EncodeGithubComGui774umeKriePkgKrieEvents(out *jwriter.Writer, in PtraceEventSerializer) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Address != 0 {
		const prefix string = ",\"address\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((in.Address).MarshalJSON())
	}
	{
		const prefix string = ",\"request\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Request).MarshalJSON())
	}
	if in.PID != 0 {
		const prefix string = ",\"pid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.PID))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PtraceEventSerializer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB7dd357EncodeGithubComGui774umeKriePkgKrieEvents(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PtraceEventSerializer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB7dd357DecodeGithubComGui774umeKriePkgKrieEvents(l, v)
}
