/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/* Copyright (c) 2020
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of version 2 of the GNU General Public
 * License as published by the Free Software Foundation.
 */
#ifndef _KRIE_LSM_H_
#define _KRIE_LSM_H_

#define KRIE_LSM(hook_point, func) SEC("lsm/"#hook_point) int BPF_PROG(lsm_security_##hook_point) { return func(ctx); }

__attribute__((always_inline)) int generic_lsm_func(void *ctx) {
    struct process_context_t *process_ctx = new_process_context();
    if (process_ctx == NULL) {
        // should never happen, ignore
        return 0;
    }
    fill_process_context(process_ctx);

    u32 action = krie_run_context_check(ctx, process_ctx);
    return krie_lsm_enforce_policy(ctx, process_ctx, action);
};

KRIE_LSM(binder_set_context_mgr, generic_lsm_func)
KRIE_LSM(binder_transaction, generic_lsm_func)
KRIE_LSM(binder_transfer_binder, generic_lsm_func)
KRIE_LSM(binder_transfer_file, generic_lsm_func)
KRIE_LSM(ptrace_access_check, generic_lsm_func)
KRIE_LSM(ptrace_traceme, generic_lsm_func)
KRIE_LSM(capget, generic_lsm_func)
KRIE_LSM(capset, generic_lsm_func)
KRIE_LSM(capable, generic_lsm_func)
KRIE_LSM(quotactl, generic_lsm_func)
KRIE_LSM(quota_on, generic_lsm_func)
KRIE_LSM(syslog, generic_lsm_func)
KRIE_LSM(bprm_creds_for_exec, generic_lsm_func)
KRIE_LSM(bprm_creds_from_file, generic_lsm_func)
KRIE_LSM(fs_context_dup, generic_lsm_func)
KRIE_LSM(fs_context_parse_param, generic_lsm_func)
KRIE_LSM(sb_eat_lsm_opts, generic_lsm_func)
KRIE_LSM(sb_mnt_opts_compat, generic_lsm_func)
KRIE_LSM(sb_remount, generic_lsm_func)
KRIE_LSM(sb_kern_mount, generic_lsm_func)
KRIE_LSM(sb_show_options, generic_lsm_func)
KRIE_LSM(sb_statfs, generic_lsm_func)
KRIE_LSM(sb_mount, generic_lsm_func)
KRIE_LSM(sb_umount, generic_lsm_func)
KRIE_LSM(sb_pivotroot, generic_lsm_func)
KRIE_LSM(sb_set_mnt_opts, generic_lsm_func)
KRIE_LSM(sb_clone_mnt_opts, generic_lsm_func)
KRIE_LSM(move_mount, generic_lsm_func)
KRIE_LSM(dentry_init_security, generic_lsm_func)
KRIE_LSM(dentry_create_files_as, generic_lsm_func)
KRIE_LSM(path_notify, generic_lsm_func)
KRIE_LSM(inode_init_security, generic_lsm_func)
KRIE_LSM(inode_init_security_anon, generic_lsm_func)
KRIE_LSM(inode_create, generic_lsm_func)
KRIE_LSM(inode_link, generic_lsm_func)
KRIE_LSM(inode_unlink, generic_lsm_func)
KRIE_LSM(inode_symlink, generic_lsm_func)
KRIE_LSM(inode_mkdir, generic_lsm_func)
KRIE_LSM(inode_rmdir, generic_lsm_func)
KRIE_LSM(inode_mknod, generic_lsm_func)
KRIE_LSM(inode_rename, generic_lsm_func)
KRIE_LSM(inode_readlink, generic_lsm_func)
KRIE_LSM(inode_follow_link, generic_lsm_func)
KRIE_LSM(inode_permission, generic_lsm_func)
KRIE_LSM(inode_setattr, generic_lsm_func)
KRIE_LSM(inode_getattr, generic_lsm_func)
KRIE_LSM(inode_setxattr, generic_lsm_func)
KRIE_LSM(inode_getxattr, generic_lsm_func)
KRIE_LSM(inode_listxattr, generic_lsm_func)
KRIE_LSM(inode_removexattr, generic_lsm_func)
KRIE_LSM(inode_need_killpriv, generic_lsm_func)
KRIE_LSM(inode_killpriv, generic_lsm_func)
KRIE_LSM(inode_getsecurity, generic_lsm_func)
KRIE_LSM(inode_setsecurity, generic_lsm_func)
KRIE_LSM(inode_listsecurity, generic_lsm_func)
KRIE_LSM(inode_copy_up, generic_lsm_func)
KRIE_LSM(inode_copy_up_xattr, generic_lsm_func)
KRIE_LSM(kernfs_init_security, generic_lsm_func)
KRIE_LSM(file_permission, generic_lsm_func)
KRIE_LSM(file_ioctl, generic_lsm_func)
KRIE_LSM(mmap_file, generic_lsm_func)
KRIE_LSM(mmap_addr, generic_lsm_func)
KRIE_LSM(file_mprotect, generic_lsm_func)
KRIE_LSM(file_lock, generic_lsm_func)
KRIE_LSM(file_fcntl, generic_lsm_func)
KRIE_LSM(file_send_sigiotask, generic_lsm_func)
KRIE_LSM(file_receive, generic_lsm_func)
KRIE_LSM(file_open, generic_lsm_func)
KRIE_LSM(task_alloc, generic_lsm_func)
KRIE_LSM(cred_alloc_blank, generic_lsm_func)
KRIE_LSM(kernel_act_as, generic_lsm_func)
KRIE_LSM(kernel_create_files_as, generic_lsm_func)
KRIE_LSM(kernel_module_request, generic_lsm_func)
KRIE_LSM(kernel_load_data, generic_lsm_func)
KRIE_LSM(kernel_post_load_data, generic_lsm_func)
KRIE_LSM(kernel_read_file, generic_lsm_func)
KRIE_LSM(kernel_post_read_file, generic_lsm_func)
KRIE_LSM(task_fix_setuid, generic_lsm_func)
KRIE_LSM(task_fix_setgid, generic_lsm_func)
KRIE_LSM(task_setpgid, generic_lsm_func)
KRIE_LSM(task_getpgid, generic_lsm_func)
KRIE_LSM(task_getsid, generic_lsm_func)
KRIE_LSM(task_setnice, generic_lsm_func)
KRIE_LSM(task_setioprio, generic_lsm_func)
KRIE_LSM(task_getioprio, generic_lsm_func)
KRIE_LSM(task_prlimit, generic_lsm_func)
KRIE_LSM(task_setrlimit, generic_lsm_func)
KRIE_LSM(task_setscheduler, generic_lsm_func)
KRIE_LSM(task_getscheduler, generic_lsm_func)
KRIE_LSM(task_movememory, generic_lsm_func)
KRIE_LSM(task_kill, generic_lsm_func)
KRIE_LSM(task_prctl, generic_lsm_func)
KRIE_LSM(ipc_permission, generic_lsm_func)
KRIE_LSM(msg_queue_associate, generic_lsm_func)
KRIE_LSM(msg_queue_msgctl, generic_lsm_func)
KRIE_LSM(msg_queue_msgsnd, generic_lsm_func)
KRIE_LSM(msg_queue_msgrcv, generic_lsm_func)
KRIE_LSM(shm_associate, generic_lsm_func)
KRIE_LSM(shm_shmctl, generic_lsm_func)
KRIE_LSM(shm_shmat, generic_lsm_func)
KRIE_LSM(sem_associate, generic_lsm_func)
KRIE_LSM(sem_semctl, generic_lsm_func)
KRIE_LSM(sem_semop, generic_lsm_func)
KRIE_LSM(getprocattr, generic_lsm_func)
KRIE_LSM(setprocattr, generic_lsm_func)
KRIE_LSM(netlink_send, generic_lsm_func)
KRIE_LSM(ismaclabel, generic_lsm_func)
KRIE_LSM(secid_to_secctx, generic_lsm_func)
KRIE_LSM(secctx_to_secid, generic_lsm_func)
KRIE_LSM(inode_notifysecctx, generic_lsm_func)
KRIE_LSM(inode_setsecctx, generic_lsm_func)
KRIE_LSM(inode_getsecctx, generic_lsm_func)
KRIE_LSM(locked_down, generic_lsm_func)
KRIE_LSM(bpf, generic_lsm_func)
KRIE_LSM(bpf_map, generic_lsm_func)
KRIE_LSM(bpf_prog, generic_lsm_func)
KRIE_LSM(perf_event_open, generic_lsm_func)
KRIE_LSM(perf_event_alloc, generic_lsm_func)
KRIE_LSM(perf_event_free, generic_lsm_func)
KRIE_LSM(perf_event_read, generic_lsm_func)
KRIE_LSM(perf_event_write, generic_lsm_func)
KRIE_LSM(unix_stream_connect, generic_lsm_func)
KRIE_LSM(unix_may_send, generic_lsm_func)
KRIE_LSM(socket_create, generic_lsm_func)
KRIE_LSM(socket_post_create, generic_lsm_func)
KRIE_LSM(socket_socketpair, generic_lsm_func)
KRIE_LSM(socket_bind, generic_lsm_func)
KRIE_LSM(socket_connect, generic_lsm_func)
KRIE_LSM(socket_listen, generic_lsm_func)
KRIE_LSM(socket_accept, generic_lsm_func)
KRIE_LSM(socket_sendmsg, generic_lsm_func)
KRIE_LSM(socket_recvmsg, generic_lsm_func)
KRIE_LSM(socket_getsockname, generic_lsm_func)
KRIE_LSM(socket_getpeername, generic_lsm_func)
KRIE_LSM(socket_getsockopt, generic_lsm_func)
KRIE_LSM(socket_setsockopt, generic_lsm_func)
KRIE_LSM(socket_shutdown, generic_lsm_func)
KRIE_LSM(socket_getpeersec_stream, generic_lsm_func)
KRIE_LSM(socket_getpeersec_dgram, generic_lsm_func)
KRIE_LSM(inet_conn_request, generic_lsm_func)
KRIE_LSM(secmark_relabel_packet, generic_lsm_func)
KRIE_LSM(tun_dev_alloc_security, generic_lsm_func)
KRIE_LSM(tun_dev_create, generic_lsm_func)
KRIE_LSM(tun_dev_attach_queue, generic_lsm_func)
KRIE_LSM(tun_dev_attach, generic_lsm_func)
KRIE_LSM(tun_dev_open, generic_lsm_func)
KRIE_LSM(sctp_assoc_request, generic_lsm_func)
KRIE_LSM(sctp_bind_connect, generic_lsm_func)

#endif